version: '3.9'

services:
  web:
    build: .
    command: ["/bin/sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: 'False'
      ALLOWED_HOSTS: "localhost 127.0.0.1"
      POSTGRES_ENGINE: django.db.backends.postgresql
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  db:
    image: docker.arvancloud.ir/postgres:16.3
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

volumes:
  db: